import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import randimg from "../public/randomai.jpg"
// import study from './study';

import styles2 from '@/styles/index.module.css';
import React from 'react';
import { useState } from 'react';



const inter = Inter({ subsets: ['latin']})

//document.body.style.backgroundColor = "black";




export default function Home() {
  const [subject, setSubject] = useState("python");
  const [hours, setHours] = useState(10);
  const [resources, setResources] = useState('video')
  const [goal, setGoal] = useState('to become a data scientist')

  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState('');

  // const [userInput, setUserInput] = useState('')
  // const [todoList, setTodoList] = useState([])



  // const Index = () => {
 
  //   const [userInput2, setUserInput] = useState('')
  //   const [todoList, setTodoList] = useState([''])
  //   const handleChange = (e: any) => {
  //    // e.preventDefault()
  
  //     setUserInput(e.target.value)
      
  //   }
  
  //   const handleSubmit = (e: any) => {
  //    // e.preventDefault()
  
  //     setTodoList([
  //       userInput2,
  //       ...todoList
  //     ])
  //   }
  // }

  async function onSubmit(e: any) {
    e.preventDefault();
    if (loading) {
      return;
    }
    try {
        setLoading(true);
        setResult('');
        const response = await fetch('/api/generate-plan', {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
        },
        body: JSON.stringify({ subject, hours, resources, goal }),
        });
        const data = await response.json();
        setResult(data.result.replaceAll('\n', '<br />'));
    } catch(e) {
        alert("Failed to generate plan! Try Later!")
    } finally {
        setLoading(false);
    }

  }
  return (
    <>
    
      <Head>
        
        <title>AI Study Planner Webpage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      

      <main className={styles.main} >
        <p style={{height: 150}}>  </p>
        <div className={styles.center}></div>

        <div className = {styles.box}>
          <p className = {styles.gradient}>
            AI&nbsp;
          </p>
          <p>
            Study Planner
          </p>
        </div>

        <div className={styles.description}>
          
          <a 
            href = "/"
            className={styles.card}>
            Home&nbsp;
          </a>

          <a 
            href="#study-planner"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer">
            Study Planner&nbsp;
          </a>

          {/* <a 
            href="#todo"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer">
            To-Do&nbsp;
          </a> */}
          
          
        </div>

        <div >
          <p style={{height: 200}}></p>
          <p className={styles.header}> Welcome!</p>
        </div>
        <div>
          <p className = {styles.bodyp} >
            Welcome to our AI-powered study planner! 
            Are you looking for a smarter way to study? Our study planner harnesses 
            the power of artificial intelligence to help you achieve your academic goals. 
            Our study planner can create a personalized study plan for your individual needs, 
            including the option to schedule your studies over a specific 
            number of days. Take the first step towards academic success and 
            start using our AI-powered study planner today! &nbsp;
          </p>
          <p className = {styles.logo}>
            <Image src={randimg} alt="missing image" width={1000} height = {500} />
          
            {/* <Image
              className={styles.logo}
              src="./randomai.svg"
              alt="image not found"
              width={1000}
              height={500}
              priority
            /> */}
          </p>
          <p style={{height: 200}}></p>
          

        </div>

        
        <h3 id = "study-planner">Generate a Study Plan ☕📚📖✍🎧</h3>
            <form onSubmit={onSubmit}>

            <label>What would you like to learn?</label>
            <input
                type="text"
                name="subject"
                placeholder="Enter a subject"
                value={subject}
                onChange={(e) => setSubject(e.target.value)}
            />

            <label>Number of hours in a week you can commit</label>
            <input
                type="number"
                min={1}
                max={168}
                name="hours"
                placeholder="Enter numbers of hours"
                value={hours}
                onChange={(e) => setHours(Number.parseInt(e.target.value))}
            />

            <label>How do you prefer learning?</label>
            <select
                name="resources"
                value={resources}
                onChange={(e) => setResources(e.target.value)}
            >
                <option value="video">Video</option>
                <option value="woman">Webpages</option>
                <option value="Video, Webpages, Practice">Video, Webpages, Practice</option>
            </select>


            <label>Why are you learning? Your goal?</label>
            <input
                type="text"
                name="goal"
                placeholder="Enter your goal"
                value={goal}
                onChange={(e) => setGoal(e.target.value)}
            />

            <input type="submit" value="Generate a plan" />
            </form>
            {loading && (
            <div>
                <h3>Looking for the best plan to learn</h3>
                <img src="/loading.gif" className={styles.loading} />
            </div>
            )}
            {result && ( 
            <div className={styles.result} dangerouslySetInnerHTML={{ __html: result }}/>
            )}

        <p style={{height: 200}}></p>
          {/* <p
            id = "todo"
            className = {styles.header}
            >
            To-Do
          </p>  */}
        

        {/* <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Doc<span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://www.linkedin.com/in/eunice-kim-225625212/"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Eunice <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Computer Science
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Templates <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div> */}
      </main>

        

    </>
  )
}
